version: "3.0"

volumes:
  mongo-db:

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: smarthome
      MONGO_INITDB_ROOT_PASSWORD: smarthome
    volumes:
      - mongo-db:/data/db
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: smarthome
      ME_CONFIG_MONGODB_ADMINPASSWORD: smarthome
      ME_CONFIG_MONGODB_URL: mongodb://smarthome:smarthome@mongo:27017/