micronaut:
  application:
    name: smarthome
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/static/**"
        paths: classpath:static
mongodb:
  uri: mongodb://smarthome:smarthome@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/
db:
  name: 'smarthome'
  sensor-data: 'sensor.data'